# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish_library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build
        working-directory: lib
        run: yarn build:prod

      - name: Prepare package
        working-directory: lib
        run: |
          mkdir package
          cp ../README.md package/
          cp ../LICENSE package/
          cp package.json package/
          cp -r dist package/

      - name: Publish
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          workspace: "lib/package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # You need to set this in your repo settings